/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./theme/views/About.vue')['default']
    Archives: typeof import('./theme/views/Archives.vue')['default']
    Artalk: typeof import('./theme/components/Plugins/Comments/Artalk.vue')['default']
    ArticleGPT: typeof import('./theme/components/Aside/Widgets/ArticleGPT.vue')['default']
    Aside: typeof import('./theme/components/Aside/index.vue')['default']
    Background: typeof import('./theme/components/Background.vue')['default']
    Banner: typeof import('./theme/components/Banner.vue')['default']
    CatOrTag: typeof import('./theme/views/CatOrTag.vue')['default']
    Checkbox: typeof import('./theme/components/Tags/Checkbox.vue')['default']
    Clock: typeof import('./theme/components/Aside/Widgets/Clock.vue')['default']
    Comments: typeof import('./theme/components/Plugins/Comments/index.vue')['default']
    Control: typeof import('./theme/components/Control.vue')['default']
    Copyright: typeof import('./theme/components/Copyright.vue')['default']
    Countdown: typeof import('./theme/components/Aside/Widgets/Countdown.vue')['default']
    Date: typeof import('./theme/components/Aside/Widgets/Date.vue')['default']
    Footer: typeof import('./theme/components/Footer.vue')['default']
    FooterLink: typeof import('./theme/components/FooterLink.vue')['default']
    Hello: typeof import('./theme/components/Aside/Widgets/Hello.vue')['default']
    Home: typeof import('./theme/views/Home.vue')['default']
    LazyLoader: typeof import('./theme/components/LazyLoader.vue')['default']
    Link: typeof import('./theme/views/Link.vue')['default']
    LinkCard: typeof import('./theme/components/Tags/LinkCard.vue')['default']
    LinkList: typeof import('./theme/components/List/LinkList.vue')['default']
    Loading: typeof import('./theme/components/Loading.vue')['default']
    Message: typeof import('./theme/components/Message.vue')['default']
    MobileMenu: typeof import('./theme/components/MobileMenu.vue')['default']
    Modal: typeof import('./theme/components/Modal.vue')['default']
    Nav: typeof import('./theme/components/Nav.vue')['default']
    NextPost: typeof import('./theme/components/NextPost.vue')['default']
    NotFound: typeof import('./theme/views/NotFound.vue')['default']
    Page: typeof import('./theme/views/Page.vue')['default']
    Pagination: typeof import('./theme/components/Pagination.vue')['default']
    Player: typeof import('./theme/components/Player.vue')['default']
    Post: typeof import('./theme/views/Post.vue')['default']
    PostList: typeof import('./theme/components/List/PostList.vue')['default']
    Project: typeof import('./theme/views/Project.vue')['default']
    References: typeof import('./theme/components/References.vue')['default']
    RelatedPost: typeof import('./theme/components/RelatedPost.vue')['default']
    RewardBtn: typeof import('./theme/components/RewardBtn.vue')['default']
    RightMenu: typeof import('./theme/components/RightMenu.vue')['default']
    Search: typeof import('./theme/components/Search.vue')['default']
    Settings: typeof import('./theme/components/Settings.vue')['default']
    SiteData: typeof import('./theme/components/Aside/Widgets/SiteData.vue')['default']
    Slider: typeof import('./theme/components/Tags/Slider.vue')['default']
    Tags: typeof import('./theme/components/Aside/Widgets/Tags.vue')['default']
    Toc: typeof import('./theme/components/Aside/Widgets/Toc.vue')['default']
    Twikoo: typeof import('./theme/components/Plugins/Comments/Twikoo.vue')['default']
    TypeBar: typeof import('./theme/components/List/TypeBar.vue')['default']
  }
}
